const COUNTRY_DATA = {
"Japan":{flag:"🇯🇵",capital:"Tokyo",continent:"Asia",population:"125M",facts:[
{e:"💡",t:"Japan has more than 5.5 million vending machines — roughly one for every 23 people — selling everything from hot soup to umbrellas."},
{e:"🎭",t:"There's a festival called 'Hadaka Matsuri' where thousands of men wearing only loincloths compete to grab sacred sticks thrown by a priest."},
{e:"🍽️",t:"Kit Kat has released over 300 unique flavors in Japan, including wasabi, sake, sweet potato, and matcha."},
{e:"🏛️",t:"The world's oldest company, Kongō Gumi, operated in Japan for 1,400 years (578–2006) building Buddhist temples."},
{e:"🌿",t:"The island of Ōkunoshima is overrun by hundreds of friendly wild rabbits, earning it the nickname 'Rabbit Island.'"},
{e:"🎵",t:"Karaoke was invented in Kobe in 1971 by Daisuke Inoue, who never patented his invention and earned nothing from it."},
{e:"��",t:"Japanese trains are so punctual that if a train is even 1 minute late, passengers receive a formal delay certificate for their employers."},
{e:"🗣️",t:"Japanese has three writing systems used simultaneously: hiragana, katakana, and kanji — one of the world's most complex literacy requirements."},
{e:"⚽",t:"Japan's 'Bo-Taoshi' is a wild sport where 150 players attack and defend a single pole — described as a mix of rugby, capture the flag, and chaos."},
{e:"🍽️",t:"Slurping noodles loudly in Japan is considered polite — it signals that you're enjoying the meal and enhances the flavor."}
]},
"Brazil":{flag:"🇧🇷",capital:"Brasília",continent:"South America",population:"214M",facts:[
{e:"🌿",t:"The Amazon Rainforest produces about 20% of the world's oxygen but consumes nearly all of it — the ocean is Earth's real lung."},
{e:"🎭",t:"Brazil's Carnival in Salvador de Bahia, not Rio, is actually the largest street party in the world with 2 million people daily."},
{e:"🍽️",t:"Brazilians put condensed milk (leite condensado) on practically everything — pizza, fruit, cake, and even plain bread."},
{e:"💡",t:"The city of Curitiba pioneered exchanging bags of recyclables for bus tokens in the 1990s, inspiring global recycling programs."},
{e:"🏛️",t:"Brasília, the capital, was built from scratch in just 41 months (1956–1960) and is shaped like an airplane when viewed from above."},
{e:"🎵",t:"Bossa nova was born in a tiny apartment in Rio's Copacabana in 1958 when João Gilberto reinvented samba with jazz harmonies."},
{e:"🌿",t:"Brazil has the highest biodiversity of any country: over 56,000 plant species, 1,700 bird species, and 700 mammal species."},
{e:"⚽",t:"Pelé's hometown of Três Corações has a heart-shaped lake that formed naturally — 'três corações' means 'three hearts.'"},
{e:"🗣️",t:"Brazil is the only Portuguese-speaking country in the Americas, surrounded entirely by Spanish-speaking neighbors."},
{e:"💡",t:"The Brazilian butt lift is actually named after the country because Brazilian surgeons pioneered the technique in the 1960s."}
]},
"Iceland":{flag:"��🇸",capital:"Reykjavík",continent:"Europe",population:"370K",facts:[
{e:"💡",t:"Iceland has no standing army, navy, or air force — and has been that way since the country was founded in 930 AD."},
{e:"🎭",t:"Icelanders still believe in elves ('Huldufólk'). Road construction has been rerouted to avoid disturbing rocks where elves supposedly live."},
{e:"🍽️",t:"Hákarl is fermented shark buried underground for months. Even Andrew Zimmern called it the worst thing he's ever eaten."},
{e:"🌿",t:"Iceland grows bananas in greenhouses heated by geothermal energy — it's actually Europe's largest banana producer."},
{e:"🏛️",t:"The Althing, Iceland's parliament founded in 930 AD, is the oldest surviving parliament in the world still in operation."},
{e:"🎵",t:"Iceland has more musicians per capita than any other country — Björk, Sigur Rós, and Of Monsters and Men all come from this tiny nation."},
{e:"💡",t:"There's an Icelandic Naming Committee that must approve all baby names to ensure they're compatible with Icelandic grammar."},
{e:"🗣️",t:"Modern Icelanders can still read 800-year-old Viking sagas in their original language — Icelandic has barely changed."},
{e:"🌿",t:"Iceland has no mosquitoes. Scientists believe the unique climate cycle prevents their larvae from completing development."},
{e:"⚽",t:"Iceland became the smallest country to ever qualify for the FIFA World Cup in 2018, with a population of just 335,000."}
]},
"Egypt":{flag:"🇪🇬",capital:"Cairo",continent:"Africa",population:"104M",facts:[
{e:"🏛️",t:"The Great Pyramid was the tallest man-made structure for 3,800 years — until Lincoln Cathedral's spire surpassed it in 1311."},
{e:"💡",t:"Ancient Egyptians invented toothpaste, using a mixture of crushed rock salt, mint, dried iris flowers, and pepper."},
{e:"🎭",t:"Egyptian taxi drivers are famous for removing their rearview mirrors — they say 'what's behind doesn't matter.'"},
{e:"🍽️",t:"Koshari, Egypt's national dish, is a carb-loaded mix of rice, lentils, pasta, and chickpeas — originally a peasant's meal."},
{e:"🌿",t:"95% of Egypt's population lives along the Nile River, occupying just 5% of the country's total land area."},
{e:"🎵",t:"Umm Kulthum's funeral in 1975 drew 4 million mourners — more than any head of state in history. She's called 'Star of the East.'"},
{e:"💡",t:"Cleopatra lived closer in time to the Moon landing (1969) than to the construction of the Great Pyramid (~2560 BC)."},
{e:"🗣️",t:"Egyptian Arabic is the most widely understood Arabic dialect thanks to Egypt's massive film and music industry."},
{e:"⚽",t:"Egypt's Al Ahly football club has won the African Champions League more times than any other club: over 10 titles."},
{e:"🏛️",t:"Ancient Egyptians loved cats so much that killing one, even accidentally, was punishable by death."}
]},
"India":{flag:"🇮🇳",capital:"New Delhi",continent:"Asia",population:"1.4B",facts:[
{e:"💡",t:"India's Kumbh Mela gathering is so massive (75 million people in 2019) it's visible from space."},
{e:"🎭",t:"The Living Root Bridges of Meghalaya are made by training tree roots across rivers — some are over 500 years old and still growing stronger."},
{e:"🍽️",t:"India has the world's largest vegetarian population. Around 400 million Indians don't eat meat — more than the entire US population."},
{e:"🏛️",t:"The city of Varanasi is one of the oldest continuously inhabited cities in the world, with settlements dating back to 11,000 BCE."},
{e:"🌿",t:"India's Western Ghats contain over 325 globally threatened species, making them one of the world's eight 'hottest hotspots' of biological diversity."},
{e:"🎵",t:"The Indian raga system has specific melodies prescribed for different times of day and seasons — playing the wrong one is considered a serious mistake."},
{e:"💡",t:"The Indian Space Research Organisation (ISRO) sent a spacecraft to Mars for $74 million — less than the budget of the movie 'Gravity.'"},
{e:"��️",t:"India has 22 official languages and over 19,500 dialects. The country's currency notes print the denomination in 15 different scripts."},
{e:"⚽",t:"Kabaddi, India's ancient sport of tag-wrestling, requires players to hold their breath while raiding — they must chant 'kabaddi' to prove it."},
{e:"🏛️",t:"The Mughal Emperor Shah Jahan commissioned the Taj Mahal in 1632 — it took 22 years and 20,000 workers to complete."}
]},
"Mexico":{flag:"🇲🇽",capital:"Mexico City",continent:"North America",population:"130M",facts:[
{e:"🎭",t:"Día de los Muertos isn't sad — families build altars, cook feasts, and spend the night in cemeteries celebrating their deceased loved ones."},
{e:"🍽️",t:"Chapulines (fried grasshoppers with chili and lime) have been a protein-rich snack in Oaxaca for thousands of years."},
{e:"🏛️",t:"The Aztec capital Tenochtitlan was built on a lake and had causeways, aqueducts, and floating gardens — it amazed Spanish conquistadors."},
{e:"🌿",t:"Mexico's Cave of Crystals contains selenite crystals up to 12 meters long — the largest natural crystals ever found on Earth."},
{e:"💡",t:"Mexico introduced chocolate, vanilla, corn, tomatoes, avocados, and chili peppers to the rest of the world."},
{e:"🎵",t:"Mariachi music was added to UNESCO's Intangible Cultural Heritage list. A full mariachi ensemble requires at least 8 musicians."},
{e:"💡",t:"Mexico City is sinking at a rate of ~50cm per year because it was built on a drained lake bed and groundwater is being depleted."},
{e:"🗣️",t:"Mexico has 68 recognized indigenous languages. Nahuatl, the Aztec language, gave English words like 'chocolate,' 'tomato,' and 'avocado.'"},
{e:"⚽",t:"Mexico's Lucha Libre wrestlers are cultural icons — their masks are so sacred that losing one in a match is considered the ultimate humiliation."},
{e:"🌿",t:"The monarch butterfly migration covers 4,800 km from Canada to a tiny forest in Michoacán — one of nature's greatest spectacles."}
]},
"Australia":{flag:"🇦🇺",capital:"Canberra",continent:"Oceania",population:"26M",facts:[
{e:"🌿",t:"Australia has more camels than any Arab country — roughly 1 million feral camels roam the outback after being imported in the 1800s."},
{e:"💡",t:"Australia lost a war against emus in 1932. The military deployed soldiers with machine guns against the birds — and the emus won."},
{e:"🍽️",t:"Vegemite is made from spent brewer's yeast. Australians consume 22 million jars a year, though most foreigners find it revolting."},
{e:"🎭",t:"Aboriginal Australians have the oldest continuous culture on Earth — over 65,000 years, with oral histories dating back to the last Ice Age."},
{e:"🏛️",t:"Melbourne was almost named 'Batmania' after the explorer John Batman. The name was used briefly before being changed."},
{e:"🎵",t:"The didgeridoo is one of the oldest wind instruments, played by Aboriginal Australians for at least 1,500 years."},
{e:"🌿",t:"The Great Barrier Reef is the largest living structure on Earth — it's even visible from space and spans 2,300 km."},
{e:"💡",t:"Australia is wider than the moon. The continent spans 4,000 km while the moon's diameter is only 3,400 km."},
{e:"⚽",t:"Australian Rules Football was codified in 1859 — predating most major sports codes including American football and basketball."},
{e:"🗣️",t:"Australia has no official language. English is the de facto language, but over 250 Aboriginal languages were spoken before colonization."}
]},
"Morocco":{flag:"🇲🇦",capital:"Rabat",continent:"Africa",population:"37M",facts:[
{e:"🏛️",t:"The University of al-Qarawiyyin in Fez, founded in 859 AD by a woman named Fatima al-Fihri, is the world's oldest existing university."},
{e:"🎭",t:"The Jemaa el-Fnaa square in Marrakech transforms nightly into an open-air circus of storytellers, snake charmers, and musicians."},
{e:"🍽️",t:"Moroccan tagine is cooked in a cone-shaped clay pot that returns condensation to the dish — it's a self-basting system invented centuries ago."},
{e:"🌿",t:"Morocco's Argan trees are famously climbed by goats who eat the fruit. The trees are endemic to Morocco and nowhere else on Earth."},
{e:"💡",t:"Morocco has the world's largest solar farm, Noor-Ouarzazate, which covers an area the size of 3,500 football fields."},
{e:"🎵",t:"Gnawa music, rooted in sub-Saharan spiritual traditions, uses hypnotic bass rhythms played on a three-stringed bass lute called a guembri."},
{e:"💡",t:"Moroccan riads (traditional houses) are built with no external windows — all rooms face a central courtyard for privacy and cooling."},
{e:"🗣️",t:"Moroccans typically speak 3–4 languages: Darija (Moroccan Arabic), French, possibly Amazigh, and increasingly English."},
{e:"⚽",t:"Morocco became the first African and Arab nation to reach a FIFA World Cup semifinal in 2022, captivating the entire world."},
{e:"🌿",t:"The Sahara Desert advances into Morocco each year, and the country has planted millions of trees in a 'Green Wall' effort to stop it."}
]},
"Italy":{flag:"🇮🇹",capital:"Rome",continent:"Europe",population:"59M",facts:[
{e:"🏛️",t:"Italy has the most UNESCO World Heritage Sites of any country in the world (58+), including Pompeii, Venice, and the Amalfi Coast."},
{e:"🍽️",t:"Italians consume 23 kg of pasta per person per year. Putting cream in carbonara or breaking spaghetti will genuinely upset an Italian."},
{e:"🎭",t:"The Palio di Siena horse race has run twice yearly since 1644. Jockeys ride bareback and the horse can win even without its rider."},
{e:"💡",t:"Italy has a free wine fountain. In Ortona, a 24/7 public fountain dispenses free red wine for pilgrims on the Cammino di San Tommaso."},
{e:"🌿",t:"Italy's Blue Grotto on Capri creates an ethereal blue glow when sunlight passes through an underwater cave opening."},
{e:"🎵",t:"Opera was invented in Florence around 1597. Italy gave the world not just the art form but all its terminology: soprano, forte, piano."},
{e:"💡",t:"There's a town called 'Colobraro' considered so unlucky that Italians won't even say its name aloud — they call it 'that village.'"},
{e:"🗣️",t:"Standard Italian didn't exist until unification in 1861. Each region still has its own dialect, many mutually unintelligible."},
{e:"⚽",t:"Italian football fans are called 'tifosi' — literally 'typhus carriers' — because their passion was compared to a fever."},
{e:"🏛️",t:"The Roman Empire's roads were so well-built that many are still used today, 2,000 years later."}
]},
"South Korea":{flag:"🇰🇷",capital:"Seoul",continent:"Asia",population:"52M",facts:[
{e:"💡",t:"South Korea has the fastest internet speed in the world. The average connection is 10x faster than the global average."},
{e:"🎭",t:"Koreans celebrate 'Black Day' on April 14th — single people who didn't receive gifts on Valentine's Day eat black noodles (jajangmyeon) together."},
{e:"🍽️",t:"There are more fried chicken restaurants in South Korea than McDonald's locations worldwide — over 36,000."},
{e:"🏛️",t:"Changdeokgung Palace's 'Secret Garden' was reserved for royalty for 500 years and contains 26,000 specimen trees."},
{e:"🌿",t:"Jeju Island has 'Haenyeo' — female free-divers, mostly grandmothers in their 70s-80s, who dive without oxygen tanks to harvest seafood."},
{e:"🎵",t:"K-pop trainees practice 14+ hours daily for years with no guarantee of debuting. The dropout rate exceeds 95%."},
{e:"💡",t:"South Korea's 'PC bangs' (gaming cafes) are open 24/7, and competitive gaming (esports) is broadcast on national television."},
{e:"🗣️",t:"King Sejong invented the Korean alphabet (Hangul) in 1443 specifically so commoners could read — scholars opposed it, calling it 'too easy.'"},
{e:"⚽",t:"South Korea co-hosted the 2002 World Cup and reached the semifinals, causing celebrations with 7 million people in the streets of Seoul."},
{e:"💡",t:"Plastic surgery is so normalized in South Korea that it's common to receive it as a graduation gift from parents."}
]},
"Peru":{flag:"🇵🇪",capital:"Lima",continent:"South America",population:"33M",facts:[
{e:"🏛️",t:"Machu Picchu's stones fit so precisely without mortar that you can't slide a knife blade between them — even after 500 years and earthquakes."},
{e:"🍽️",t:"Peru has over 4,000 varieties of native potatoes. The Incas invented freeze-drying by leaving potatoes at high altitude overnight."},
{e:"🎭",t:"The Q'eswachaka rope bridge is rebuilt entirely by hand every June using Incan techniques — a tradition spanning 600 years."},
{e:"🌿",t:"The Nazca Lines include 70+ giant geoglyphs visible only from the air, created between 500 BCE and 500 CE. Their purpose remains debated."},
{e:"💡",t:"Peru's Lake Titicaca has floating islands made of totora reeds by the Uros people — they literally live on handmade ground."},
{e:"🎵",t:"The Peruvian cajón (wooden box drum) was invented by enslaved Africans after colonizers banned their drums."},
{e:"🌿",t:"Peru's Colca Canyon is twice as deep as the Grand Canyon and home to the Andean condor, which has a 3-meter wingspan."},
{e:"🗣️",t:"Quechua, the Incan language, is still spoken by 8 million people across South America and is an official language of Peru."},
{e:"⚽",t:"Peruvian ceviche must use local limes — the acidity 'cooks' the fish. Peruvians and Ecuadorians fiercely debate who invented it."},
{e:"💡",t:"The ancient city of Caral is 5,000 years old — as old as the Egyptian pyramids — making it the oldest known city in the Americas."}
]},
"Norway":{flag:"🇳🇴",capital:"Oslo",continent:"Europe",population:"5.4M",facts:[
{e:"💡",t:"Norway has a 'silly walk' crossing signal in the town of Ørje, inspired by Monty Python's Ministry of Silly Walks sketch."},
{e:"🎭",t:"Norwegians have 'friluftsliv' — the philosophy of open-air living — and are legally guaranteed access to roam any uncultivated land."},
{e:"🍽️",t:"Brunost (brown cheese) is so beloved that a truckload catching fire in a tunnel in 2013 made international news."},
{e:"🏛️",t:"Norway's Svalbard Global Seed Vault stores 1.1 million seed samples from around the world as backup against global catastrophe."},
{e:"🌿",t:"Norway's coastline, with all its fjords, would stretch 100,000 km if straightened — more than twice around the Earth."},
{e:"🎵",t:"Norwegian black metal bands in the 1990s burned medieval churches. The scene became one of music's most notorious subcultures."},
{e:"💡",t:"Norway knighted a penguin. Sir Nils Olav III at Edinburgh Zoo holds the rank of Brigadier in the Norwegian King's Guard."},
{e:"🗣️",t:"Norway has two official written languages — Bokmål and Nynorsk — and every student must learn both."},
{e:"⚽",t:"Cross-country skiing is virtually a national religion. Babies learn to ski before they can walk, and ski waxing is a serious obsession."},
{e:"🌿",t:"The Northern Lights are visible across Norway for months. Tromsø, inside the Arctic Circle, has 2 months of total darkness in winter."}
]},
"Thailand":{flag:"🇹🇭",capital:"Bangkok",continent:"Asia",population:"72M",facts:[
{e:"💡",t:"Bangkok's full ceremonial name is 168 characters long, making it the world's longest city name. Locals just call it 'Krung Thep.'"},
{e:"🎭",t:"The Thai Monkey Buffet Festival in Lopburi serves a lavish feast to 3,000 wild monkeys annually as thanks for attracting tourists."},
{e:"🍽️",t:"Thai iced tea gets its orange color from food coloring and condensed milk — it was originally designed to be extra sweet for laborers."},
{e:"🏛️",t:"Thailand is the only Southeast Asian country never colonized by a European power — 'Thai' literally means 'free.'"},
{e:"🌿",t:"Tham Luang cave, where 12 boys were famously rescued in 2018, is actually one of the longest caves in Thailand at 10 km."},
{e:"🎵",t:"Traditional Thai music uses a pentatonic scale with no semitones, making it sound distinctively different from Western music."},
{e:"💡",t:"The Thai king's birthday determines the color people wear that day. Yellow represents Monday (the king's birth day)."},
{e:"🗣️",t:"Thai is a tonal language with 5 tones — the same syllable can mean 'new,' 'burn,' 'news,' 'silk,' or 'not' depending on pitch."},
{e:"⚽",t:"Muay Thai fighters perform a 'Wai Kru' dance before every fight — a ritualized prayer that can take several minutes."},
{e:"🌿",t:"Thailand's Erawan waterfall has 7 tiers, each named after a head of the mythological three-headed elephant Erawan."}
]},
"Turkey":{flag:"🇹🇷",capital:"Ankara",continent:"Asia/Europe",population:"85M",facts:[
{e:"🏛️",t:"Istanbul is the only city in the world that spans two continents — Europe and Asia — connected by the Bosphorus strait."},
{e:"🍽️",t:"Turkish breakfast can last hours and includes 20+ dishes: cheeses, olives, eggs, honey, jams, pastries, and unlimited tea."},
{e:"🎭",t:"Oil wrestling (Yağlı Güreş) is Turkey's national sport — competitors douse themselves in olive oil and grapple. It dates back 660 years."},
{e:"💡",t:"Turkey gave the world tulips, not the Netherlands. The Dutch imported them from the Ottoman Empire in the 1500s."},
{e:"🌿",t:"Cappadocia's fairy chimneys are volcanic rock formations that ancient people carved into homes, churches, and entire underground cities."},
{e:"🎵",t:"Turkish 'makam' music uses microtones (intervals smaller than semitones) that don't exist in Western music, creating hauntingly unique melodies."},
{e:"💡",t:"Santa Claus was born in Turkey. Saint Nicholas was a 4th-century bishop from Myra in modern-day Antalya province."},
{e:"🗣️",t:"Turkey's 1928 alphabet revolution switched from Arabic script to Latin letters overnight — the entire population had to re-learn reading."},
{e:"⚽",t:"Galatasaray football fans created a 'Welcome to Hell' banner in the 1990s that became one of the most iconic moments in European football."},
{e:"🏛️",t:"Göbekli Tepe, a 12,000-year-old temple in southeastern Turkey, predates Stonehenge by 6,000 years and rewrote human history."}
]},
"New Zealand":{flag:"🇳🇿",capital:"Wellington",continent:"Oceania",population:"5.1M",facts:[
{e:"🌿",t:"New Zealand was the last major landmass settled by humans — Polynesians arrived only around 1250 CE."},
{e:"💡",t:"New Zealand has more sheep than people — roughly 26 million sheep to 5 million humans."},
{e:"🎭",t:"The Māori haka isn't just a war dance — it's performed at weddings, funerals, and even in parliament to show respect."},
{e:"🍽️",t:"The Kiwi burger at McDonald's NZ includes a fried egg and beetroot — both considered essential burger toppings by New Zealanders."},
{e:"🏛️",t:"New Zealand was the first country to give women the right to vote in 1893 — 27 years before the United States."},
{e:"🎵",t:"The Māori taonga pūoro (traditional instruments) include a 'purerehua' — a bullroarer that produces eerie wind sounds."},
{e:"🌿",t:"The Whanganui River was granted legal personhood in 2017 — it has the same rights as a human being under New Zealand law."},
{e:"💡",t:"New Zealand's Fiordland gets up to 8 meters of rain per year, making it one of the wettest inhabited places on Earth."},
{e:"⚽",t:"Rugby is practically a religion. The All Blacks have a winning percentage above 77% — the most dominant team in any sport's history."},
{e:"🗣️",t:"Te Reo Māori experienced a dramatic revival — from near extinction in the 1970s to now being taught in over 1,000 schools."}
]},
"Colombia":{flag:"🇨🇴",capital:"Bogotá",continent:"South America",population:"52M",facts:[
{e:"🌿",t:"Colombia has more bird species than any other country — over 1,900 — nearly 20% of all bird species on Earth."},
{e:"🎭",t:"Barranquilla's Carnival is the second-largest in the world after Rio, featuring cumbia dancers and elaborate animal costumes."},
{e:"🍽️",t:"Colombians put cheese in their hot chocolate, dunking salty white cheese until it melts into a gooey, sweet-salty combo."},
{e:"💡",t:"Colombia's Caño Cristales river turns five colors (red, yellow, green, blue, black) due to aquatic plants — it's called 'the River of Five Colors.'"},
{e:"🏛️",t:"The Lost City (Ciudad Perdida) was built 650 years before Machu Picchu and requires a 4-day jungle trek to reach."},
{e:"🎵",t:"Cumbia originated from enslaved Africans, indigenous, and Spanish cultures blending — it's now the rhythmic backbone of Latin American music."},
{e:"💡",t:"The town of Guatapé is painted in bright, elaborate zócalos (bas-reliefs) on every building, making it one of the most colorful places on Earth."},
{e:"🗣️",t:"Colombian Spanish is often considered the 'clearest' Spanish dialect. Bogotá was once called the 'Athens of South America.'"},
{e:"⚽",t:"Colombia's footballer Higuita invented the 'scorpion kick' save in 1995 at Wembley — one of football's most iconic moments."},
{e:"🌿",t:"Colombia produces 90% of the world's emeralds, and Muzo, the main mining town, has been fought over for 500 years."}
]},
"Greece":{flag:"🇬🇷",capital:"Athens",continent:"Europe",population:"10.4M",facts:[
{e:"🏛️",t:"Ancient Athens' democracy had a process called 'ostracism' — citizens voted to exile someone for 10 years by writing names on pottery shards."},
{e:"🍽️",t:"Greeks consume more olive oil per capita than any country — about 20 liters per person per year."},
{e:"🎭",t:"The Greek evil eye (mati) is taken seriously — blue glass charms hang in nearly every home, car, and business for protection."},
{e:"��",t:"Greece has more archaeological museums than any other country in the world, reflecting its unparalleled ancient heritage."},
{e:"🌿",t:"Santorini's caldera was formed by one of the largest volcanic eruptions in recorded history, which may have destroyed the Minoan civilization."},
{e:"🎵",t:"Rebetiko, Greece's 'urban blues,' was created by refugees and outcasts in port cities. It was banned by the government in the 1930s."},
{e:"💡",t:"Greece has between 1,200 and 6,000 islands depending on what you count — only 227 are inhabited."},
{e:"🗣️",t:"Greek has been spoken continuously for 3,400 years, making it the oldest recorded living language in Europe."},
{e:"⚽",t:"Greece's shock victory at Euro 2004 is considered the biggest upset in football tournament history — they were 150-1 outsiders."},
{e:"🏛️",t:"The ancient Greeks invented the alarm clock — Plato used a water clock that whistled at dawn to wake his students."}
]},
"Kenya":{flag:"🇰🇪",capital:"Nairobi",continent:"Africa",population:"54M",facts:[
{e:"💡",t:"Kenya's M-Pesa mobile money system, launched in 2007, lets people bank via basic phones — it transformed finance across Africa."},
{e:"🌿",t:"The Great Rift Valley running through Kenya is slowly splitting Africa in two — in 50 million years, East Africa will be a separate continent."},
{e:"🎭",t:"The Maasai's jumping dance (adumu) is a competitive display where warriors leap vertically from standing — the highest jumper wins the most respect."},
{e:"🍽️",t:"Nyama Choma (roasted meat) is Kenya's social food — business deals, friendships, and celebrations all happen around a charcoal grill."},
{e:"🏛️",t:"Fort Jesus in Mombasa changed hands nine times between the Portuguese and Omanis, making it one of the most fought-over forts in history."},
{e:"🎵",t:"Benga music, born in Kenya in the 1940s, fused traditional Luo rhythms with electric guitar — it influenced music across East Africa."},
{e:"💡",t:"Kenya produces some of the world's finest black tea — it's the third-largest tea producer globally, after China and India."},
{e:"⚽",t:"Kenyan marathon runners dominate because many grow up running to school at altitude — Iten, the 'Home of Champions,' sits at 2,400m elevation."},
{e:"🗣️",t:"Swahili, Kenya's national language, is a Bantu language with heavy Arabic influence — 'safari' is the Swahili word for 'journey.'"},
{e:"🌿",t:"Lake Nakuru can turn pink with millions of flamingos — up to 2 million have been recorded at once."}
]},
"Canada":{flag:"🇨🇦",capital:"Ottawa",continent:"North America",population:"39M",facts:[
{e:"💡",t:"Canada has more lakes than the rest of the world combined — over 2 million lakes, containing 20% of the world's fresh water."},
{e:"🎭",t:"The town of Churchill, Manitoba is the 'Polar Bear Capital of the World' — bears walk through town and people leave cars unlocked as escape shelters."},
{e:"🍽️",t:"Poutine (fries, gravy, cheese curds) was considered low-class food until the 2000s. Now gourmet poutineries charge $20+ per plate."},
{e:"🏛️",t:"Canada's border with the US is the longest international border in the world — 8,891 km, most of it completely unguarded wilderness."},
{e:"🌿",t:"Canada has a forest called the Great Bear Rainforest that's larger than Ireland and home to the all-white 'Spirit Bear' (Kermode bear)."},
{e:"🎵",t:"Canadian content laws ('CanCon') require radio stations to play at least 35% Canadian music — it helped launch Drake, Celine Dion, and The Weeknd."},
{e:"💡",t:"Alert, Nunavut is the northernmost permanently inhabited place on Earth — it's closer to Moscow than to Toronto."},
{e:"🗣️",t:"Canada has two official languages. New Brunswick is the only officially bilingual province — all services are in English and French."},
{e:"⚽",t:"Canada's national sport isn't hockey — it's lacrosse (summer) and hockey (winter). Lacrosse was played by Indigenous peoples for centuries."},
{e:"🌿",t:"The Bay of Fundy has the highest tides in the world — up to 16 meters, enough to submerge a four-story building."}
]},
"Vietnam":{flag:"🇻🇳",capital:"Hanoi",continent:"Asia",population:"99M",facts:[
{e:"💡",t:"Vietnam is the world's second-largest coffee producer after Brazil — and Vietnamese iced coffee with condensed milk (cà phê sữa đá) is legendary."},
{e:"🎭",t:"Water puppetry, unique to Vietnam, originated in rice paddies where farmers performed puppet shows in flooded fields."},
{e:"🍽️",t:"Phở was only invented in the early 1900s in northern Vietnam, making it surprisingly young for such an iconic dish."},
{e:"🏛️",t:"The Củ Chi tunnels stretch over 250 km — an entire underground city with hospitals, kitchens, and living quarters used during the Vietnam War."},
{e:"🌿",t:"Hang Sơn Đoòng is the world's largest cave — so enormous that it has its own weather system, jungle, and river inside."},
{e:"🎵",t:"Vietnamese đàn bầu is a one-string instrument that produces an impossibly wide range of notes through harmonics — it sounds otherworldly."},
{e:"💡",t:"Motorbikes outnumber cars 20 to 1 in Vietnam. Ho Chi Minh City has 9 million motorbikes — crossing the street is a choreographed act of faith."},
{e:"🗣️",t:"Vietnamese uses 6 tones. The word 'ma' alone can mean ghost, mother, but, horse, tomb, or rice seedling depending on tone."},
{e:"⚽",t:"Vietnam's traditional martial art Vovinam includes aerial scissors kicks where fighters leap and grip their opponent's neck with their legs."},
{e:"��",t:"Ha Long Bay has 1,600 limestone islands and islets, many containing hidden caves and lakes — its name means 'Descending Dragon.'"}
]},
"Argentina":{flag:"🇦🇷",capital:"Buenos Aires",continent:"South America",population:"46M",facts:[
{e:"🎭",t:"Tango was born in the slums of Buenos Aires among immigrants — it was considered scandalous and only became respectable after Paris embraced it."},
{e:"🍽️",t:"Argentinians consume the most beef per capita in the world — the weekly 'asado' (barbecue) is a sacred family ritual lasting 4+ hours."},
{e:"💡",t:"Argentina has the widest avenue in the world — Avenida 9 de Julio in Buenos Aires has 16 lanes and takes 3 light cycles to cross on foot."},
{e:"🏛️",t:"Ushuaia in Patagonia is the southernmost city in the world — it's closer to Antarctica than to Buenos Aires."},
{e:"🌿",t:"Perito Moreno Glacier is one of the few glaciers in the world that's still growing. It periodically calves massive chunks with thunderous crashes."},
{e:"🎵",t:"Argentina's greatest tango singer, Carlos Gardel, has a statue in Buenos Aires where fans still place lit cigarettes in his hand."},
{e:"💡",t:"Every Argentine province has its own mate ritual. Sharing mate (herbal tea) is a social bond — refusing a shared mate is considered rude."},
{e:"🗣️",t:"Argentine Spanish uses 'vos' instead of 'tú' and has a distinctive Italian-inflected accent because 60% of Argentines have Italian ancestry."},
{e:"⚽",t:"Diego Maradona's 'Hand of God' goal and 'Goal of the Century' happened in the same 1986 match — within 4 minutes of each other."},
{e:"🌿",t:"Iguazú Falls consists of 275 individual waterfalls spanning 2.7 km. Eleanor Roosevelt reportedly exclaimed 'Poor Niagara!' upon seeing them."}
]},
"Germany":{flag:"🇩🇪",capital:"Berlin",continent:"Europe",population:"84M",facts:[
{e:"💡",t:"There are over 1,500 different beers brewed in Germany — and the Reinheitsgebot (beer purity law) from 1516 is still in effect."},
{e:"🎭",t:"Germany has a 'quiet hours' law (Ruhezeit). Mowing your lawn on Sundays, drilling, or even playing loud music can result in fines."},
{e:"🍽️",t:"Germany has over 1,500 varieties of sausage (Wurst). The currywurst was invented in Berlin in 1949 and 800 million are eaten yearly."},
{e:"🏛️",t:"The Berlin Wall fell because of a bureaucratic blunder — a confused spokesman accidentally announced border openings 'immediately' on live TV."},
{e:"🌿",t:"The Black Forest got its name because the dense canopy of evergreen trees blocks so much sunlight that the forest floor is perpetually dark."},
{e:"🎵",t:"Germany's Berghain nightclub in Berlin has the world's toughest door policy — the bouncer Sven Marquardt is more famous than most DJs."},
{e:"💡",t:"Germany has a word for everything: 'Kummerspeck' means weight gained from emotional overeating — literally 'grief bacon.'"},
{e:"🗣️",t:"German compound words can be infinitely long. 'Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz' was an actual law name (63 letters)."},
{e:"⚽",t:"Germany's 7-1 victory over Brazil in the 2014 World Cup semifinal happened in Brazil — 5 goals were scored in 18 minutes."},
{e:"🏛️",t:"Neuschwanstein Castle inspired Disney's Sleeping Beauty Castle. It was built by 'Mad' King Ludwig II, who spent only 11 nights there."}
]},
"South Africa":{flag:"🇿🇦",capital:"Pretoria",continent:"Africa",population:"60M",facts:[
{e:"💡",t:"South Africa has three capital cities: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial)."},
{e:"🎭",t:"The Ubuntu philosophy — 'I am because we are' — is a core South African value. Desmond Tutu called it the essence of being human."},
{e:"🍽️",t:"Biltong (dried cured meat) is South Africa's national snack. Unlike jerky, it's air-dried, not smoked, giving it a unique tender texture."},
{e:"🏛️",t:"Robben Island, where Mandela was imprisoned for 18 years, now has tours led by former political prisoners."},
{e:"🌿",t:"The Cape Floral Kingdom is the smallest of the world's 6 plant kingdoms but has the highest concentration of plant species: 9,000+ species."},
{e:"🎵",t:"South African house music ('Amapiano') exploded globally in the 2020s, characterized by log drums, jazz harmonies, and bouncing basslines."},
{e:"💡",t:"South Africa performed the world's first human heart transplant in 1967 at Groote Schuur Hospital in Cape Town."},
{e:"🗣️",t:"South Africa has 11 official languages — the most of any country. The national anthem includes lyrics in 5 different languages."},
{e:"⚽",t:"The 1995 Rugby World Cup final, where Mandela wore a Springbok jersey, is considered one of sport's greatest moments of reconciliation."},
{e:"🌿",t:"The Drakensberg Mountains contain the highest concentration of San rock art in the world — some paintings are over 3,000 years old."}
]},
"United States":{flag:"🇺🇸",capital:"Washington D.C.",continent:"North America",population:"331M",facts:[
{e:"💡",t:"The US Interstate Highway System requires one mile in every five to be straight — originally so planes could land on them in emergencies (though debated)."},
{e:"🎭",t:"Groundhog Day in Punxsutawney, PA draws 40,000 people to watch a rodent 'predict' the weather. Phil has been 'right' about 39% of the time."},
{e:"🍽️",t:"Americans eat roughly 100 acres of pizza per day — about 3 billion pizzas per year."},
{e:"🏛️",t:"The Library of Congress has over 170 million items, including a rough draft of the Declaration of Independence with edits by Benjamin Franklin."},
{e:"🌿",t:"Yellowstone sits atop a supervolcano. Its magma chamber could fill the Grand Canyon more than 11 times over."},
{e:"🎵",t:"The blues, jazz, rock 'n' roll, hip hop, and country music all originated in the US — arguably the most musically influential country in history."},
{e:"💡",t:"Alaska is simultaneously the most northern, western, AND eastern state in the US — its Aleutian Islands cross the 180° meridian."},
{e:"🗣️",t:"The US has no official language at the federal level. Over 350 languages are spoken, including Navajo, which was used as an unbreakable code in WWII."},
{e:"⚽",t:"The Super Bowl is so massive that it's effectively an unofficial national holiday — avocado sales spike 80% in the week before."},
{e:"🌿",t:"Hawaii's Mauna Kea, measured from its base on the ocean floor, is over 10,000m tall — taller than Everest."}
]},
"United Kingdom":{flag:"🇬🇧",capital:"London",continent:"Europe",population:"67M",facts:[
{e:"💡",t:"The London Underground's 'Mind the Gap' recording was kept for years at one station after the voice actor's widow asked — it was her late husband."},
{e:"🎭",t:"The Brits queue so seriously that forming an orderly line is considered a near-sacred cultural practice. Queue-jumping can provoke genuine outrage."},
{e:"🍽️",t:"The British drink about 100 million cups of tea per day — roughly 36 billion cups per year."},
{e:"🏛️",t:"The Tower of London has had ravens for centuries. Legend says if they ever leave, the kingdom will fall — so their wings are clipped."},
{e:"🌿",t:"The UK's coastline is 19,491 miles long. Due to fractals, the more precisely you measure it, the longer it gets — the 'coastline paradox.'"},
{e:"🎵",t:"The Beatles, Rolling Stones, Led Zeppelin, Pink Floyd, Queen, Radiohead, Adele, and Amy Winehouse are all British — a staggering musical output."},
{e:"💡",t:"The British invented the postage stamp, TV, WWW, telephone, jet engine, and discovered penicillin — all from a country smaller than Oregon."},
{e:"🗣️",t:"English has the largest vocabulary of any language — over 170,000 words in current use, plus 47,000 obsolete words."},
{e:"⚽",t:"England invented modern football in 1863 but didn't win a World Cup until 1966 — and hasn't won one since."},
{e:"🏛️",t:"Big Ben is actually the name of the bell inside the tower, not the tower itself. The tower's official name is Elizabeth Tower."}
]},
"France":{flag:"🇫🇷",capital:"Paris",continent:"Europe",population:"68M",facts:[
{e:"💡",t:"France is the most visited country on Earth with ~90 million tourists per year — more than its own population."},
{e:"🎭",t:"The French have a legal 'right to disconnect' — employers cannot email workers after hours. Work-life balance is literally the law."},
{e:"🍽️",t:"A French meal is an art form. UNESCO added 'the gastronomic meal of the French' to its Intangible Cultural Heritage list in 2010."},
{e:"🏛️",t:"The Eiffel Tower was supposed to be temporary — built for the 1889 World's Fair and scheduled for demolition after 20 years."},
{e:"🌿",t:"France spans 12 time zones (thanks to overseas territories), more than any other country including Russia."},
{e:"🎵",t:"Edith Piaf's 'La Vie en Rose' is one of the most covered songs in history. She was only 4'8\" tall but had a voice that filled stadiums."},
{e:"💡",t:"France has a timezone on every continent: Europe, South America (French Guiana), Africa (Réunion), Oceania (New Caledonia), and Antarctica."},
{e:"🗣️",t:"French was the language of international diplomacy for centuries. 29 countries have French as an official language."},
{e:"⚽",t:"France's national football team is nicknamed 'Les Bleus.' Their 2018 World Cup squad had players with roots in 17 different countries."},
{e:"🌿",t:"Mont Blanc in the French Alps is the highest peak in Western Europe at 4,808m, and it's still growing a few millimeters per year."}
]},
"Spain":{flag:"🇪🇸",capital:"Madrid",continent:"Europe",population:"47M",facts:[
{e:"🎭",t:"La Tomatina festival in Buñol involves 20,000 people throwing 150,000 tomatoes at each other for one hour every August."},
{e:"🍽️",t:"Spaniards eat dinner at 9-10 PM — the latest in Europe. The country is in the wrong timezone (should be GMT like UK) due to Franco aligning with Hitler."},
{e:"🏛️",t:"The Sagrada Familia in Barcelona has been under construction since 1882 — longer than the Egyptian pyramids took to build."},
{e:"💡",t:"Spain has more bars per capita than any other EU country — roughly 1 bar for every 132 people."},
{e:"🌿",t:"Spain's Canary Islands are named after dogs ('Canis' in Latin), not canaries. The birds were named after the islands."},
{e:"🎵",t:"Flamenco wasn't originally Spanish — it was developed by the Romani people (gitanos) of Andalusia, blending Indian, Arab, and Jewish influences."},
{e:"💡",t:"The Spanish siesta is declining — only 18% of Spaniards still nap regularly, despite the cultural stereotype."},
{e:"🗣️",t:"Spanish is the second most spoken native language worldwide (after Mandarin), with 475 million native speakers."},
{e:"⚽",t:"FC Barcelona's Camp Nou holds 99,354 people. On match days, it becomes the third largest 'city' in Catalonia by population."},
{e:"🌿",t:"Tenerife's Teide volcano is the third tallest volcanic structure in the world and Spain's highest peak."}
]},
"China":{flag:"🇨🇳",capital:"Beijing",continent:"Asia",population:"1.4B",facts:[
{e:"💡",t:"China uses about 80 billion pairs of disposable chopsticks per year — equivalent to 20 million trees."},
{e:"🎭",t:"Chinese New Year is the world's largest annual human migration — about 3 billion trips are made during the 40-day travel season."},
{e:"🍽️",t:"Chinese cuisine has 8 recognized regional traditions, each as different from one another as French food is from Mexican."},
{e:"🏛️",t:"The Great Wall is not visible from space with the naked eye — but China's air pollution sometimes is."},
{e:"🌿",t:"China planted so many trees between 1990 and 2015 that its forest coverage increased by an area the size of France."},
{e:"🎵",t:"The Chinese guqin, a 3,000-year-old stringed instrument, was so revered that Confucius himself was said to play it daily."},
{e:"💡",t:"China built a 57-story skyscraper in 19 working days using prefabricated modules — it would take years in most countries."},
{e:"🗣️",t:"Mandarin Chinese has 4 tones. The syllable 'ma' can mean mother, hemp, horse, or scold depending on tone."},
{e:"⚽",t:"Table tennis is China's national sport. The country has won 28 of 37 total Olympic gold medals ever awarded in the sport."},
{e:"🏛️",t:"The Terracotta Army contains 8,000 unique soldiers — no two faces are alike. It was discovered accidentally by farmers digging a well in 1974."}
]},
"Russia":{flag:"🇷🇺",capital:"Moscow",continent:"Europe/Asia",population:"144M",facts:[
{e:"💡",t:"Russia spans 11 time zones. When it's midnight in Kaliningrad, it's already 10 AM in Kamchatka."},
{e:"🎭",t:"Russians have a superstition about shaking hands over a threshold — it's considered extremely bad luck."},
{e:"🍽️",t:"Borscht (beet soup) is such a cultural staple that Ukraine and Russia have a heated debate over which country 'invented' it."},
{e:"🏛️",t:"The Moscow Metro is essentially an underground palace — stations feature chandeliers, marble walls, mosaics, and bronze sculptures."},
{e:"🌿",t:"Lake Baikal in Siberia holds 20% of the world's unfrozen fresh water — more than all the Great Lakes combined."},
{e:"🎵",t:"Tchaikovsky, Rachmaninoff, Stravinsky, and Shostakovich made Russia one of the most influential countries in classical music history."},
{e:"💡",t:"Russia is so vast that it contains a full one-eighth of the Earth's total land area — larger than Pluto's surface."},
{e:"🗣️",t:"Russian uses the Cyrillic alphabet, which was created by two Greek monks (Cyril and Methodius) in the 9th century."},
{e:"⚽",t:"Chess is practically a national pastime. Russia has produced more world chess champions than any other country."},
{e:"🌿",t:"The Siberian taiga is the largest forest on Earth, producing more oxygen than the Amazon and absorbing massive amounts of CO₂."}
]},
"Indonesia":{flag:"🇮🇩",capital:"Jakarta",continent:"Asia",population:"275M",facts:[
{e:"💡",t:"Indonesia has 17,508 islands — only about 6,000 are inhabited. No one has visited them all."},
{e:"🎭",t:"Bali's 'Nyepi' (Day of Silence) shuts down the entire island: no flights, no internet, no lights, no travel for 24 hours."},
{e:"🍽️",t:"Nasi Goreng (fried rice) is the national dish and is eaten for breakfast, lunch, and dinner — each vendor has a unique recipe."},
{e:"🏛️",t:"Borobudur is the world's largest Buddhist temple, built in the 9th century with 2,672 panels and 504 Buddha statues."},
{e:"🌿",t:"Indonesia's Komodo dragons are the largest living lizards, reaching 3 meters. Their saliva contains 50+ bacterial strains."},
{e:"🎵",t:"Gamelan music uses tuned bronze instruments in orchestras of up to 40 players — the sound is hypnotic and nothing else resembles it."},
{e:"💡",t:"Indonesia's capital is moving from Jakarta to Nusantara on Borneo — Jakarta is literally sinking into the sea."},
{e:"🗣️",t:"Indonesia has 700+ languages but united them with 'Bahasa Indonesia' — a standardized form of Malay — as one national language."},
{e:"⚽",t:"Badminton is Indonesia's passion — the country has won more Olympic gold medals in badminton than in all other sports combined."},
{e:"🌿",t:"Sumatra's rainforests are one of only two places on Earth where orangutans, tigers, elephants, and rhinos coexist in the wild."}
]},
"Nigeria":{flag:"🇳🇬",capital:"Abuja",continent:"Africa",population:"220M",facts:[
{e:"💡",t:"Nigeria's film industry 'Nollywood' produces about 2,500 films per year — more than Hollywood, second only to India's Bollywood."},
{e:"🎭",t:"Nigeria has over 250 ethnic groups. The three largest — Hausa, Yoruba, and Igbo — each have populations larger than many countries."},
{e:"🍽️",t:"Jollof rice is Nigeria's proudest dish. The 'Jollof wars' with Ghana over who makes it better is one of West Africa's fiercest debates."},
{e:"🏛️",t:"The Benin Bronzes (from present-day Nigeria) are among the finest metal sculptures ever created — made by the Edo people from the 13th century."},
{e:"🌿",t:"Nigeria has the largest mangrove forest in Africa, stretching across the Niger Delta — it's one of the most biodiverse wetlands on Earth."},
{e:"🎵",t:"Afrobeats, pioneered by Fela Kuti, has become one of the most dominant music genres globally — Burna Boy and Wizkid carry the torch."},
{e:"💡",t:"Lagos is projected to become the world's largest city by 2100, potentially surpassing 100 million residents."},
{e:"🗣️",t:"English is Nigeria's official language, but Nigerian Pidgin English is the true lingua franca, spoken by over 75 million people."},
{e:"⚽",t:"Nigeria's Super Eagles are one of Africa's most successful football teams — their 1996 Olympic gold medal shocked the world."},
{e:"🏛️",t:"The Nok civilization, one of Africa's oldest, produced stunning terracotta sculptures over 2,500 years ago in central Nigeria."}
]},
"Ethiopia":{flag:"🇪🇹",capital:"Addis Ababa",continent:"Africa",population:"120M",facts:[
{e:"💡",t:"Ethiopia is 7-8 years behind the rest of the world — it uses its own calendar with 13 months, 12 of 30 days and one of 5 or 6."},
{e:"🎭",t:"Ethiopia is the only African country never colonized by a European power. Italians tried twice and failed spectacularly."},
{e:"🍽️",t:"Injera, Ethiopia's spongy flatbread, doubles as plate AND utensil. You tear pieces off to scoop up stews — no forks needed."},
{e:"🏛️",t:"The rock-hewn churches of Lalibela were carved directly out of solid rock in the 12th century — they're often called the 'Eighth Wonder of the World.'"},
{e:"🌿",t:"Ethiopia is the birthplace of coffee. Legend says a goatherd named Kaldi noticed his goats dancing after eating coffee berries."},
{e:"🎵",t:"Ethiopian jazz ('Ethio-jazz') fuses traditional pentatonic scales with funk and jazz — it sounds like nothing else on Earth."},
{e:"💡",t:"Lucy, the 3.2 million-year-old hominid fossil, was discovered in Ethiopia in 1974 and named after the Beatles song 'Lucy in the Sky with Diamonds.'"},
{e:"🗣️",t:"Amharic, Ethiopia's official language, uses Ge'ez script — one of the oldest alphabets in continuous use, with 238 characters."},
{e:"⚽",t:"Ethiopian runners have dominated long-distance running for decades. Abebe Bikila won the 1960 Olympic marathon running barefoot."},
{e:"🌿",t:"The Simien Mountains are called 'the roof of Africa' — home to gelada baboons, Ethiopian wolves, and Walia ibex found nowhere else."}
]},
"Cuba":{flag:"🇨🇺",capital:"Havana",continent:"North America",population:"11M",facts:[
{e:"💡",t:"Cuba has two currencies. Until 2021, tourists used CUC while locals used CUP — one of the world's strangest monetary systems."},
{e:"🎭",t:"Havana's crumbling architecture is frozen in time — 50s-era buildings, vintage American cars, and hand-painted signs create a living time capsule."},
{e:"🍽️",t:"Cuban sandwiches were actually invented by Cuban immigrants in Florida — in Cuba, they eat 'pan con lechón' instead."},
{e:"🏛️",t:"Old Havana is a UNESCO World Heritage Site with over 900 historical monuments crammed into a few square kilometers."},
{e:"🌿",t:"Cuba has the world's smallest frog (Monte Iberia eleuth, under 10mm) and the world's smallest bird (the Bee Hummingbird, 5cm)."},
{e:"🎵",t:"The Buena Vista Social Club album (1997) brought Cuban son music to the world — recorded with musicians in their 70s-90s."},
{e:"💡",t:"Cuba has a higher literacy rate (99.8%) than the United States, despite being a developing nation."},
{e:"🗣️",t:"Cuban Spanish drops 's' sounds and swallows consonants so heavily that other Spanish speakers sometimes struggle to understand it."},
{e:"⚽",t:"Baseball, not football, is Cuba's national sport. The country has won 25 Baseball World Cup titles."},
{e:"🌿",t:"Cuba's Viñales Valley has dramatic limestone mogotes (flat-topped hills) that look like they belong in a fantasy novel."}
]},
"Jordan":{flag:"🇯🇴",capital:"Amman",continent:"Asia",population:"11M",facts:[
{e:"🏛️",t:"Petra's Treasury was carved directly into a sandstone cliff face by the Nabataeans over 2,000 years ago — it's 40 meters tall."},
{e:"💡",t:"The Dead Sea, bordering Jordan, is the lowest point on Earth's surface (430m below sea level) and so salty you float effortlessly."},
{e:"🎭",t:"Jordanian hospitality is legendary — refusing a cup of tea or coffee can be seen as deeply disrespectful."},
{e:"🍽️",t:"Mansaf, Jordan's national dish, is lamb cooked in dried yogurt served over rice — it's eaten communally with the right hand."},
{e:"🌿",t:"Wadi Rum's Martian-like red desert has been used as a stand-in for Mars in movies like 'The Martian' and 'Dune.'"},
{e:"🎵",t:"Bedouin music uses the rababa (one-stringed fiddle) to accompany poetry recitations that can last hours."},
{e:"💡",t:"Jordan is one of the most water-scarce countries on Earth — yet Amman has been continuously inhabited for over 11,000 years."},
{e:"🗣️",t:"Jordanian Arabic uses unique words from ancient Arabic extinct elsewhere — linguists study it to understand how Arabic evolved."},
{e:"⚽",t:"Jordan's national football team nearly qualified for the 2014 World Cup — they lost in a playoff to Uruguay in a heartbreaking match."},
{e:"🏛️",t:"The Citadel in Amman contains ruins from the Bronze Age, Roman, Byzantine, and Umayyad periods — layer upon layer of history."}
]},
"Chile":{flag:"🇨🇱",capital:"Santiago",continent:"South America",population:"19M",facts:[
{e:"💡",t:"Chile is the longest north-south country in the world — stretching 4,300 km, equivalent to Norway to Nigeria."},
{e:"🎭",t:"Easter Island (Rapa Nui) belongs to Chile and sits 3,700 km offshore — one of the most remote inhabited places on Earth."},
{e:"🍽️",t:"Chileans consume the most bread per capita in South America and 2nd most in the world — 'marraqueta' rolls are sacred."},
{e:"🏛️",t:"Chile's Atacama Desert has been used by NASA to test Mars rovers because its soil is nearly identical to the Martian surface."},
{e:"🌿",t:"Torres del Paine in Patagonia is considered one of the most beautiful national parks on Earth, with glaciers, lakes, and granite towers."},
{e:"🎵",t:"Víctor Jara was a folk singer killed during Pinochet's coup in 1973. His songs became anthems of resistance across Latin America."},
{e:"💡",t:"The Atacama Desert is the driest non-polar desert on Earth. Some weather stations there have NEVER recorded rain."},
{e:"🗣️",t:"Chilean Spanish is notoriously fast and full of slang — other Spanish speakers joke that Chileans invented their own language."},
{e:"⚽",t:"Chile won back-to-back Copa América titles in 2015 and 2016 despite never having won the tournament before."},
{e:"🌿",t:"Chile's Lake General Carrera has 'Marble Caves' — surreal blue caverns carved by water into solid marble over 6,000 years."}
]},
"Nepal":{flag:"🇳🇵",capital:"Kathmandu",continent:"Asia",population:"30M",facts:[
{e:"💡",t:"Nepal's flag is the only national flag that isn't rectangular — it's two stacked triangles, and there's a precise mathematical formula to draw it."},
{e:"🎭",t:"The Kumari is a living goddess — a young girl selected through rigorous tests who is worshipped until she reaches puberty."},
{e:"🍽️",t:"Dal Bhat (lentil soup with rice) is eaten twice daily by most Nepalis. The saying goes: 'Dal Bhat power, 24 hour.'"},
{e:"🏛️",t:"Lumbini, the birthplace of the Buddha, is in Nepal — not India. This is a common misconception that Nepalis will correct firmly."},
{e:"🌿",t:"Eight of the world's fourteen 8,000-meter peaks are in Nepal, including Everest (8,849m), the highest point on Earth."},
{e:"🎵",t:"The sarangi (a small Nepali fiddle) is played by wandering Gandharva musicians who travel village to village singing news and stories."},
{e:"💡",t:"Nepal's calendar is 56 years ahead of the Western calendar. The year 2024 AD is 2081 BS (Bikram Sambat) in Nepal."},
{e:"🗣️",t:"Nepal has 123 languages spoken by less than 30 million people — one of the highest linguistic densities on Earth."},
{e:"⚽",t:"Cricket is hugely popular in Nepal despite it not being a traditional cricket nation — the Nepal cricket team has a passionate fanbase."},
{e:"🌿",t:"The Annapurna Circuit trek passes through every climate zone from tropical to arctic within just 200 km."}
]},
"Philippines":{flag:"🇵🇭",capital:"Manila",continent:"Asia",population:"114M",facts:[
{e:"💡",t:"Text messaging was invented as a culture in the Philippines — Filipinos sent the world's first SMS-based political movement (EDSA II in 2001)."},
{e:"🎭",t:"Filipino 'Bayanihan' means neighbors literally carrying your house to a new location — the entire community lifts the structure and walks."},
{e:"🍽️",t:"Adobo (meat braised in vinegar, soy sauce, and garlic) is the unofficial national dish — every family has a closely guarded recipe."},
{e:"🏛️",t:"The Philippines was named after King Philip II of Spain in 1542 — it's the only Asian country named after a European monarch."},
{e:"🌿",t:"The Chocolate Hills of Bohol are 1,268 perfectly cone-shaped hills that turn brown in summer — nobody fully understands how they formed."},
{e:"🎵",t:"Filipinos are legendary karaoke singers. The karaoke machine was actually invented by a Filipino named Roberto del Rosario."},
{e:"💡",t:"The Philippines has the most social media users per capita in the world — averaging 10+ hours online per day."},
{e:"🗣️",t:"Filipino (Tagalog-based) borrowed heavily from Spanish — 'kumusta' (how are you) comes from '¿cómo está?'"},
{e:"⚽",t:"Basketball, not football, is the Philippines' most popular sport — despite having no NBA-sized players. Street courts are everywhere."},
{e:"🌿",t:"The Philippine Eagle is the world's largest eagle by wing surface area and is critically endangered with fewer than 400 left."}
]},
"Portugal":{flag:"🇵🇹",capital:"Lisbon",continent:"Europe",population:"10M",facts:[
{e:"💡",t:"Portugal decriminalized ALL drugs in 2001. HIV infections dropped 95% and drug-related deaths fell dramatically."},
{e:"🎭",t:"Fado music expresses 'saudade' — a deep longing for something absent. UNESCO added it to its Intangible Heritage list."},
{e:"🍽️",t:"Portugal has 365 recipes for cod (bacalhau) — one for each day of the year. The fish is actually imported from Norway."},
{e:"🏛️",t:"Livraria Lello in Porto, built in 1906, inspired J.K. Rowling's vision of Hogwarts — she lived in Porto while writing Harry Potter."},
{e:"🌿",t:"The Azores archipelago sits on the Mid-Atlantic Ridge — literally on the seam between tectonic plates, 1,500 km from mainland Portugal."},
{e:"🎵",t:"Portuguese-speaking countries span four continents. Lusophone culture connects Brazil, Angola, Mozambique, Cape Verde, and more."},
{e:"💡",t:"The Vasco da Gama Bridge in Lisbon is the longest in Europe at 12.3 km — so long that its curvature accounts for the Earth's roundness."},
{e:"🗣️",t:"Portuguese is spoken by 260 million people worldwide — it's the most spoken language in South America (because of Brazil)."},
{e:"⚽",t:"Cristiano Ronaldo, from Madeira, is the all-time top scorer in international football with 130+ goals."},
{e:"🌿",t:"Portugal's Algarve coast has some of Europe's most stunning sea caves, carved by Atlantic waves into golden limestone cliffs."}
]},
"Croatia":{flag:"🇭🇷",capital:"Zagreb",continent:"Europe",population:"3.9M",facts:[
{e:"💡",t:"The necktie was invented in Croatia. Croatian mercenaries wore knotted scarves in the 17th century — the French called them 'cravates.'"},
{e:"🎭",t:"Dubrovnik's old city was the primary filming location for King's Landing in Game of Thrones."},
{e:"🍽️",t:"Croatian truffle hunters use specially trained dogs to find truffles in Istria — one of the largest white truffles ever (1.31 kg) was found here."},
{e:"🏛️",t:"Diocletian's Palace in Split isn't a ruin — 3,000 people still live inside the 1,700-year-old Roman emperor's retirement home."},
{e:"🌿",t:"Plitvice Lakes has 16 terraced lakes connected by waterfalls. The travertine barriers that separate them grow about 1cm per year."},
{e:"🎵",t:"Klapa singing (a cappella harmonies from Dalmatia) is a UNESCO Intangible Cultural Heritage — fishermen sing it in port town squares."},
{e:"💡",t:"Nikola Tesla was born in Smiljan, Croatia (then Austria-Hungary). Both Croatia and Serbia claim him as their own."},
{e:"🗣️",t:"Croatian, Serbian, Bosnian, and Montenegrin are essentially the same language with different names — a politically charged linguistic situation."},
{e:"⚽",t:"Croatia (pop. 3.9M) reached the 2018 World Cup Final — making them the smallest country to do so since Uruguay in 1950."},
{e:"🌿",t:"Croatia has over 1,200 islands along its coast, but only about 50 are permanently inhabited."}
]},
"Sweden":{flag:"🇸🇪",capital:"Stockholm",continent:"Europe",population:"10.4M",facts:[
{e:"💡",t:"Sweden has a 6-hour workday movement. Several companies tested it and found that employees became more productive, not less."},
{e:"🎭",t:"Swedes have 'fika' — a sacred daily coffee break with pastries. Skipping fika is practically a social offense."},
{e:"🍽️",t:"Swedish 'surströmming' (fermented herring) smells so bad that it's been banned on several airlines. Swedes eat it outdoors."},
{e:"🏛️",t:"The Vasa warship sank 20 minutes into its maiden voyage in 1628. It was salvaged 333 years later and is now Stockholm's most popular museum."},
{e:"🌿",t:"'Allemansrätten' (Right to Roam) lets anyone walk, camp, or forage on any land in Sweden — it's written into the constitution."},
{e:"🎵",t:"Sweden is the world's third-largest music exporter after the US and UK — ABBA, Avicii, Robyn, and Max Martin all came from this country of 10 million."},
{e:"💡",t:"Sweden recycles so efficiently that it imports garbage from other countries to fuel its waste-to-energy power plants."},
{e:"🗣️",t:"Swedish has a unique word 'lagom' meaning 'just the right amount' — it's an entire philosophy of balance embedded in the language."},
{e:"⚽",t:"Ice hockey rivals football for Sweden's most popular sport. The Sweden-Finland rivalry games draw over 1 million TV viewers."},
{e:"🌿",t:"Northern Sweden has the Icehotel in Jukkasjärvi — rebuilt every winter from ice blocks cut from the Torne River."}
]},
"Poland":{flag:"🇵🇱",capital:"Warsaw",continent:"Europe",population:"38M",facts:[
{e:"💡",t:"Poland's Wieliczka Salt Mine has an entire underground cathedral — complete with chandeliers, altars, and sculptures — all carved from salt."},
{e:"🎭",t:"Poland celebrates 'Fat Thursday' (Tłusty Czwartek) by collectively eating 100 million doughnuts (pączki) in a single day."},
{e:"🍽️",t:"Pierogi (filled dumplings) come in dozens of varieties. The debate over sweet vs. savory fillings can get heated at Polish family gatherings."},
{e:"🏛️",t:"Warsaw was 85% destroyed in WWII but was meticulously rebuilt — its Old Town reconstruction is so faithful it earned UNESCO status."},
{e:"🌿",t:"Białowieża Forest, straddling Poland and Belarus, is the last primeval forest in lowland Europe — home to wild European bison."},
{e:"🎵",t:"Chopin was Polish, and his heart is literally embedded in a pillar of the Holy Cross Church in Warsaw — smuggled there after his death in Paris."},
{e:"💡",t:"Marie Curie was born in Warsaw. She remains the only person to win Nobel Prizes in two different sciences (Physics and Chemistry)."},
{e:"🗣️",t:"Polish is considered one of the hardest languages to learn — it has 7 grammatical cases and consonant clusters like 'szcz' and 'prz.'"},
{e:"⚽",t:"Robert Lewandowski scored 5 goals in 9 minutes for Bayern Munich in 2015 — one of the most remarkable individual performances in football history."},
{e:"🌿",t:"The Masurian Lake District has over 2,000 lakes connected by rivers and canals — it's called 'The Land of a Thousand Lakes.'"}
]},
"Iran":{flag:"🇮🇷",capital:"Tehran",continent:"Asia",population:"87M",facts:[
{e:"🏛️",t:"Persepolis, the ceremonial capital of the Achaemenid Empire (550 BC), was so vast that Alexander the Great needed 3,000 camels to carry away its treasures."},
{e:"🎭",t:"Nowruz (Persian New Year) is celebrated by 300+ million people worldwide. It begins on the spring equinox and lasts 13 days."},
{e:"🍽️",t:"Iranian saffron is the world's finest — Iran produces 90% of the global supply. A single kilogram costs more than gold."},
{e:"💡",t:"Iran has one of the world's highest rates of nose jobs. Rhinoplasty is so common and celebrated that some people wear post-surgery bandages as a status symbol."},
{e:"🌿",t:"The Dash-e Lut desert holds the record for the highest surface temperature ever recorded on Earth: 70.7°C (159°F)."},
{e:"🎵",t:"Persian classical music uses intervals that don't exist in Western music — its 'radif' system contains over 250 melodic fragments."},
{e:"💡",t:"Iran's 'yakhchāl' (ice pits) were ancient refrigerators — Persians made ice in the desert 2,400 years ago using evaporative cooling."},
{e:"🗣️",t:"Farsi (Persian) is written in Arabic script but is an Indo-European language — it's closer to English and French than to Arabic."},
{e:"⚽",t:"Football is Iran's most popular sport. The Iran-USA World Cup match in 1998 was called 'the most politically charged game in history.'"},
{e:"🏛️",t:"The Nasir al-Mulk Mosque in Shiraz is called the 'Pink Mosque' — its stained glass windows create a kaleidoscope of color at sunrise."}
]},
"Lebanon":{flag:"🇱🇧",capital:"Beirut",continent:"Asia",population:"5.5M",facts:[
{e:"🏛️",t:"Byblos is one of the oldest continuously inhabited cities — about 7,000 years old. The word 'Bible' derives from its Greek name, Byblos."},
{e:"🍽️",t:"Lebanese cuisine is considered one of the world's finest. A traditional 'mezze' spread can have 30+ small dishes before the main course even arrives."},
{e:"🎭",t:"Lebanon is smaller than Connecticut but has 18 recognized religious communities — more diversity per square km than almost anywhere."},
{e:"💡",t:"You can ski in the mountains and swim in the Mediterranean on the same day in Lebanon — the country is only 55 km wide."},
{e:"🌿",t:"The Cedars of God grove contains trees over 1,000 years old. The cedar is Lebanon's national symbol, featured on its flag."},
{e:"🎵",t:"Fairuz is perhaps the Arab world's most beloved singer. During Lebanon's civil war, her music was the only thing both sides agreed on."},
{e:"💡",t:"Beirut has been destroyed and rebuilt 7 times throughout history — earning it the nickname 'the city that refuses to die.'"},
{e:"🗣️",t:"Lebanese switch between Arabic, French, and English mid-sentence — often within a single phrase. This trilingual mixing is called 'code-switching.'"},
{e:"⚽",t:"Basketball is more popular than football in Lebanon — the national league draws packed arenas and intense city rivalries."},
{e:"🌿",t:"The Jeita Grotto contains the world's longest known stalactite at 8.2 meters, inside a limestone cave system 9 km long."}
]},
"Madagascar":{flag:"🇲🇬",capital:"Antananarivo",continent:"Africa",population:"29M",facts:[
{e:"🌿",t:"90% of Madagascar's wildlife is found nowhere else on Earth — including 100+ species of lemurs, the island's most famous residents."},
{e:"🎭",t:"The Malagasy practice 'famadihana' — a ceremony where they exhume their dead, rewrap them in fresh cloth, and dance with the bodies."},
{e:"🍽️",t:"Rice is so central to Malagasy life that the word for 'to eat' literally means 'to eat rice.' A meal without rice isn't a meal."},
{e:"🏛️",t:"Madagascar split from India about 88 million years ago and has been evolving in isolation ever since — it's a natural laboratory of evolution."},
{e:"🌿",t:"The Avenue of the Baobabs features 800-year-old trees up to 30 meters tall — they look like they've been planted upside-down."},
{e:"🎵",t:"Malagasy music blends Southeast Asian, African, and Arabic influences — the valiha (bamboo tube zither) is the national instrument."},
{e:"💡",t:"Madagascar produces 80% of the world's natural vanilla. Real vanilla is the second most expensive spice after saffron."},
{e:"🗣️",t:"Malagasy is an Austronesian language — more closely related to languages in Borneo than to any African language, despite Madagascar's location."},
{e:"⚽",t:"Madagascar's national football team qualified for the Africa Cup of Nations for the first time in 2019 and won their first two matches."},
{e:"💡",t:"The island has 'tsingy' formations — razor-sharp limestone needles so dense that satellite imagery can't see the ground beneath them."}
]},
"Finland":{flag:"🇫🇮",capital:"Helsinki",continent:"Europe",population:"5.5M",facts:[
{e:"💡",t:"Finland has been ranked the happiest country in the world for 7 consecutive years by the World Happiness Report."},
{e:"🎭",t:"Finland hosts the World Wife Carrying Championship. The winner receives the wife's weight in beer."},
{e:"🍽️",t:"Finns consume more coffee per capita than any other country — about 12 kg per person per year (roughly 4 cups daily)."},
{e:"🏛️",t:"Finland's education system has no standardized tests, no homework until age 16, shorter school days — and consistently ranks among the world's best."},
{e:"🌿",t:"Finland has 188,000 lakes (more than any country except Canada) and 179,000 islands — it's more water than land in some regions."},
{e:"🎵",t:"Finland has more heavy metal bands per capita than any other country. There are 53.5 metal bands per 100,000 people."},
{e:"💡",t:"There are 3.3 million saunas in Finland for 5.5 million people — roughly one sauna for every 1.6 Finns."},
{e:"🗣️",t:"Finnish is not related to any nearby language. It's in the Uralic family, most closely related to Estonian and distantly to Hungarian."},
{e:"⚽",t:"Finland's national sport is pesäpallo — a uniquely Finnish version of baseball that looks similar but plays completely differently."},
{e:"🌿",t:"Lapland in northern Finland has the 'kaamos' — a period of polar night where the sun doesn't rise for up to 50 days."}
]},
"Romania":{flag:"🇷🇴",capital:"Bucharest",continent:"Europe",population:"19M",facts:[
{e:"🏛️",t:"Romania's Palace of the Parliament is the world's heaviest building and second-largest administrative building after the Pentagon."},
{e:"🎭",t:"Transylvania is a real place. Bran Castle, marketed as 'Dracula's Castle,' draws millions of visitors — though Vlad the Impaler barely spent time there."},
{e:"🍽️",t:"Mici (pronounced 'meech') — small grilled sausages without casing — are Romania's beloved street food, always served with mustard and bread."},
{e:"💡",t:"Romania's internet speed is consistently among the fastest in the world — faster than the US, UK, and most of Western Europe."},
{e:"🌿",t:"Romania has Europe's last remaining virgin forests, with trees over 400 years old — but illegal logging threatens them."},
{e:"🎵",t:"George Enescu is Romania's greatest composer. The Bucharest Athenaeum, where his music is performed, has stunning fresco-covered walls."},
{e:"💡",t:"The Merry Cemetery of Săpânța has brightly painted crosses with humorous poems about the deceased — death is celebrated, not mourned."},
{e:"🗣️",t:"Romanian is the closest living language to Latin. Romanians can partially understand Italian, Spanish, and Portuguese without studying them."},
{e:"⚽",t:"Gheorghe Hagi, 'The Maradona of the Carpathians,' led Romania to the 1994 World Cup quarterfinals — the country's golden football era."},
{e:"🌿",t:"The Danube Delta is Europe's best-preserved river delta — home to over 300 bird species and where the Danube meets the Black Sea."}
]}
};
